language: python
python:
    - "2.7"

env:
    global:
        - SPARK_HOME=/tmp/spark-1.5.1-bin-hadoop2.4

install:
    - ./install-spark.sh
    - "pip install -r requirements-test.txt"

script: ./run_tests.sh

